#!/bin/bash

set -o pipefail
set -e

controller=false
debug=false
start_time=$(date '+%s')
helm_only=false
debug_helm=
helm_install=false

while getopts "adhyik" arg; do
    case "$arg" in    
      a) controller=true ;;
      d) debug=true ;;
      h) helm_only=true ;;
      y) debug_helm="--debug" ;;
      i) helm_install=true ;;
    esac
done

echo "Controller:	${controller}"
echo "Agent:		true"
echo "Debug:		${debug}"

project_dir=$HOME/go/src/github.com/cilium/cilium
install_dir=${project_dir}/install/kubernetes

export DOCKER_REGISTRY=localhost:5000
#export DOCKER_FLAGS=--push 
export DOCKER_IMAGE_TAG=latest
export NOSTRIP=true

function notify {
	osascript -e "display notification \"$1.\" with title \"Install-Cilium\" subtitle \"$2.\" sound name \"Frog\""
}

function build_cilium {
    echo "Building Cilium"
    (cd ${project_dir} && make dev-docker-image)
    docker push localhost:5000/cilium/cilium-dev:latest
}

function build_cilium_operator {
    echo "Building Operator"
    (cd ${project_dir} && make docker-operator-generic-image)
    docker push localhost:5000/cilium/operator-generic:latest
}

function cilium-helm-install {
    echo "skipping install..."
    if [ -z "${1}" ]; then
        echo "tag not provided"
        return
    fi
    ciliumVersion=${1}
    cd ${install_dir}
    CILIUM_CI_TAG="${1}"
    action=template
    if [[ "${helm_install}" == "true" ]]; then
        action=install
    fi
    helm upgrade --install ${debug_helm} cilium ./cilium \
      --namespace kube-system \
      --set prometheus.enabled=true \
      --set operator.prometheus.enabled=true \
      --set debug.enabled=${debug} \
      --set hubble.enabled=true \
      --set image.repository=localhost:5000/cilium/cilium-dev \
      --set image.tag=$CILIUM_CI_TAG \
      --set operator.image.repository=localhost:5000/cilium/operator \
      --set operator.image.suffix="" \
      --set securityContext.privileged=true \
      --set ingressController.enabled=true \
      --set ingressController.loadbalancerMode=dedicated \
      --set kubeProxyReplacement=strict \
      --set enableCiliumEndpointSlice=true \
      --set operator.image.tag=$CILIUM_CI_TAG
    helm list -n kube-system
}
if [[ "${controller}" == "true" ]]; then
	echo "Building operator"
	build_cilium_operator
fi

if [[ "${helm_only}" == "true" ]]; then
	echo "[Info] Only applying helm charts!" 
	cilium-helm-install latest
	echo "[Info] Done applying helm charts!" 
	exit 0
fi

build_cilium
cilium-helm-install latest
echo "Rolling out Cilium DaemonSet..."
kubectl rollout restart ds cilium -n kube-system
if [[ "${controller}" == "true" ]]; then
	echo "Rolling out Cilium Operator..."
	kubectl rollout restart deployment cilium-operator -n kube-system
fi

echo "Waiting to become stable..."
kubectl wait -n kube-system --for condition=Ready pods -l=k8s-app=cilium
end_time=$(date '+%s')
notify "Cilium is ready"

#echo "Storing build data into metrics.db"
#cpus=$(nproc)
#sqlite ~/.metrics.db "insert into builds (start_time, end_time, cpus, memory) values (${start_time}, ${end_time}, ${cpus}, ${memo});"
echo "done"
