#!/bin/bash

msg() {
    echo -e "\e[32m✅\e[0m $1"
}

echo "Creating MetaLB for Kind Cluster"

range_cidr=$(docker network inspect -f '{{.IPAM.Config}}' kind-cilium --format='{{json .}}' | \
	jq -r '.IPAM.Config[] | select(.Subnet | test("^\\d{1,3}(\\.\\d{1,3}){3}(/\\d{1,2})?$")) | .Subnet')

# Convert this from cidr to "1.2.3.0-1.2.3.255" range.
IP_RANGE=$(cidr_to_range $range_cidr)

echo -e "\xF0\x9F\x94\x8C Using IP Range: ${IP_RANGE}"

cat << EOF > metallb_values.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example
  namespace: metallb-system
spec:
  addresses:
  - ${IP_RANGE} 
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
EOF

echo -e "\xE2\x8F\xB0 Installing..."
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
kubectl wait --namespace metallb-system \
                --for=condition=ready pod \
                --selector=app=metallb \
                --timeout=90s
kubectl apply -f metallb_values.yaml

msg "Done!"

kubectl -n metallb-system get pods
