#!/bin/bash

echo "Creating MetaLB for Kind Cluster"
KIND_NET_CIDR=$(docker network inspect kind -f '{{(index .IPAM.Config 0).Subnet}}')
IP_START=$(echo ${KIND_NET_CIDR} | sed "s@0.0/16@255.200@")
IP_END=$(echo ${KIND_NET_CIDR} | sed "s@0.0/16@255.250@")
IP_RANGE="${IP_START}-${IP_END}"

cat << EOF > metallb_values.yaml
configInline:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - ${IP_RANGE}
EOF

helm install \
  --namespace metallb-system \
  --create-namespace \
  --repo https://metallb.github.io/metallb metallb metallb \
  --values metallb_values.yaml

kubectl -n metallb-system get pods
