SCRIPTS_DIR=/usr/sbin/
install:
	install setns $(SCRIPTS_DIR)setns
	install kind_install_metallb $(SCRIPTS_DIR)kind_install_metallb
	install install-cilium $(SCRIPTS_DIR)install-cilium
	install cagent $(SCRIPTS_DIR)cagent
	install clogs $(SCRIPTS_DIR)clogs
